#pragma once

#undef IBOF_CONFIG_BDEV_FIO_PLUGIN
#undef IBOF_CONFIG_FE_QOS
#undef IBOF_CONFIG_GCOV
#undef IBOF_CONFIG_LIBRARY_BUILD
#undef IBOF_CONFIG_MOCK_ARRAY_PARTATION
#undef IBOF_CONFIG_MOCK_MBR
