#pragma once

#undef IBOF_CONFIG_ASAN
#undef IBOF_CONFIG_BDEV_FIO_PLUGIN
#define IBOF_CONFIG_BE_QOS 1
#undef IBOF_CONFIG_FE_QOS
#undef IBOF_CONFIG_FPIC
#undef IBOF_CONFIG_GCOV
#undef IBOF_CONFIG_LIBRARY_BUILD
#undef IBOF_CONFIG_MFS_RAID
#undef IBOF_CONFIG_MOCK_ARRAY_PARTATION
#undef IBOF_CONFIG_MOCK_MBR
#undef IBOF_CONFIG_USE_MOCK_FS
