export MODULE='"src/"'
_air:
	@$(MAKE) -C api
	@$(MAKE) -C chain
	@$(MAKE) -C collection
	@$(MAKE) -C collection/writer
	@$(MAKE) -C config
	@$(MAKE) -C data_structure
	@$(MAKE) -C input
	@$(MAKE) -C lib
	@$(MAKE) -C meta
	@$(MAKE) -C object
	@$(MAKE) -C output
	@$(MAKE) -C policy
	@$(MAKE) -C process
	@$(MAKE) -C process/processor
	@$(MAKE) -C stream
	@$(MAKE) -C target_detector
	@$(MAKE) -C thread
