export MODULE='"src/"'
_air:
	@$(MAKE) -C api
	@$(MAKE) -C chain
	@$(MAKE) -C collection
	@$(MAKE) -C config
	@$(MAKE) -C input
	@$(MAKE) -C lib
	@$(MAKE) -C meta
	@$(MAKE) -C object
	@$(MAKE) -C output
	@$(MAKE) -C policy
	@$(MAKE) -C process
	@$(MAKE) -C stream
	@$(MAKE) -C thread
	@$(MAKE) -C profile_data
	@$(MAKE) -C target_detector
