#UT_PATH, VPATH, OBJS

ifeq ($(ut),ext_mock)
# build: make ut=ext_mock -j32
UT_TESTDOUBLE_MOCK = 1
endif

ifeq ($(MFS_EXTERNAL_FAKE), 1)
MFS_TESTDOUBLE_SRCS += \
    mfs_io_api_fake.cpp \
	mfs_mgmt_api_fake.cpp 

endif

SRCS += $(MFS_TESTDOUBLE_SRCS)

###

ifeq ($(UT_TESTDOUBLE_MOCK), 1)
UT_PATH += \
	./mock/unit_test \

endif    

ifeq ($(UT_TESTDOUBLE_MOCK), 1)
UT_SRCS += \
	ut_mfs_io_api_mock.cpp  \

endif


