// generated by c_interface_gen module

#ifndef AIR_C_H
#define AIR_C_H

#include <stdint.h>
#include <stdbool.h>

enum AIR_NODE
{
    PERF_VOLUME,
    LAT_VOLUME_READ,
    LAT_VOLUME_WRITE,
    PERF_METAFS_IO,
    Q_AIO,
    Q_NVRAM,
    Q_SSD,
    Q_EVENT,
    Q_IO,
    PERF_COPY,
    PERF_BACKEND_TEST,
};

enum AIR_Basic
{
    AIR_BASE,
};

enum AIR_IOtype
{
    AIR_READ,
    AIR_WRITE,
};

enum AIR_SimpleLat
{
    AIR_BEGIN,
    AIR_END,
};

enum AIR_Range
{
    AIR_0,
    AIR_1,
    AIR_2,
    AIR_3,
    AIR_4,
    AIR_5,
};

#ifdef __cplusplus
extern "C" {
#endif

void AIR_INITIALIZE(uint32_t cpu_num);
void AIR_ACTIVATE(void);
void AIR_DEACTIVATE(void);
void AIR_FINALIZE(void);
void AIRLOG(uint32_t node_id, uint32_t filter_item, uint64_t node_index, uint64_t value);
void AIRLOG_FAKE(uint32_t node_id, uint32_t filter_item, uint64_t node_index, uint64_t value);

#ifdef __cplusplus
}
#endif

#endif // AIR_C_H
