TOP := $(abspath $(CURDIR)/../../..)

MFS_TOP_DIR :=$(abspath ../../metafs)
include $(abspath $(MFS_TOP_DIR)/../../mk)/ibof_config.mk


#SRCS += $(wildcard *.cpp)

SRCS += \
	metafs_management_api.cpp \
	metafs_file_control_api.cpp \
	metafs_io_api.cpp \
	metafs_wbt_api.cpp \

include $(TOP)/Makefile.rules 
