#!/bin/bash

# Register CLI man page
mv /etc/poseidonos-cli* /usr/share/man/man3/
makewhatis

# register poseidonos.service
mv /etc/poseidonos.service /lib/systemd/system/poseidonos.service
mv /etc/pos-exporter.service /lib/systemd/system/pos-exporter.service
systemctl daemon-reload
systemctl enable poseidonos.service
systemctl enable pos-exporter.service
