#!/bin/bash

# Register CLI man page
mv /etc/poseidonos-cli* /usr/share/man/man3/
makewhatis

# register poseidonos.service
mv /etc/poseidonos.service /lib/systemd/system/poseidonos.service
mv /etc/pos-exporter.service /lib/systemd/system/pos-exporter.service

systemctl daemon-reload
systemctl enable poseidonos.service
systemctl enable pos-exporter.service

# Prometheus Docker Container Setting
docker rm --force pos-prometheus || true

tar -xzvf /etc/pos/prometheus.tar.gz -C /etc/pos/
docker load -i /etc/pos/prometheus.tar

chown 65534:65534 /etc/pos/prometheus-data

sed -i 's/localhost/'"$(hostname -i | awk -F" " '{print $1}')"'/g' /etc/pos/pos-prometheus.yml
docker run \
    -d \
    --name pos-prometheus \
    --restart=always \
    -p 2113:9090 \
    -v /etc/pos/prometheus-data:/prometheus/data \
    -v /etc/pos/pos-prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus \
    --web.enable-admin-api \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path="/prometheus/data/" \
    --storage.tsdb.retention.time=30d
