#!/bin/bash

# remove poseidonos.servie
systemctl stop poseidonos.service
systemctl stop pos-exporter.service

systemctl disable poseidonos.service
systemctl disable pos-exporter.service

rm -rf /lib/systemd/system/poseidonos.service
rm -rf /lib/systemd/system/pos-exporter.service
systemctl reset-failed
systemctl daemon-reload

# remove pos user library and config files
rm -rf /usr/local/lib/spdk
rm -rf /usr/local/etc
rm -rf /etc/pos


# remove pos log
rm -rf /var/log/pos/*

# remove pos-prometheus container
docker rm --force pos-prometheus || true

# remove debug tool
rm -rf /usr/local/bin/trigger_core_dump
rm -rf /usr/local/bin/load_dump
