{
 "title": "POS CI Monitoring",
 "description": "You can monitor Metrics/Logs of POS CI processes",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "pos_metric_data_source", "query": "prometheus" },
   {
    "name": "CI",
    "query": {
     "query": "label_values(array_status, job)"
    }
   },
   {
    "name": "run_id",
    "query": {
     "query": "label_values(array_status{job=\"${CI:raw}\"},run_id)"
    }
   },
   { "name": "pos_log_data_source", "query": "elasticsearch" }
  ]
 },
 "panels": [
  { "title": "Metric (Array)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "array_status{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Array ID: {{array_unique_id}}"
    }
   ]
  },
  { "title": "Metric (Volume)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(read_iops{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"})",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(read_rate_bytes_per_second{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"})",
     "legendFormat": "Read BW"
    },
    {
     "expr": "sum(write_iops{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"})",
     "legendFormat": "Write IOPS"
    },
    {
     "expr": "sum(write_rate_bytes_per_second{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"})",
     "legendFormat": "Write BW"
    }
   ]
  },
  {
   "title": "Read IOPS (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "read_iops{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}}"
    }
   ]
  },
  {
   "title": "Read BW (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "read_rate_bytes_per_second{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}}"
    }
   ]
  },
  {
   "title": "Read Latency - Mean(+)/Max(-)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "read_latency_mean_ns{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}} [count: {{sample_count}}]"
    },
    {
     "expr": "read_latency_max_ns{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"} * (-1)",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}} [count: {{sample_count}}]"
    }
   ]
  },
  {
   "title": "Write IOPS (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "write_iops{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}}"
    }
   ]
  },
  {
   "title": "Write BW (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "write_rate_bytes_per_second{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}}"
    }
   ]
  },
  {
   "title": "Write Latency - Mean(+)/Max(-)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "write_latency_mean_ns{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}} [count: {{sample_count}}]"
    },
    {
     "expr": "write_latency_max_ns{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"} * (-1)",
     "legendFormat": "Vol_{{volume_id}} @ Array_{{array_id}} [count: {{sample_count}}]"
    }
   ]
  },
  { "title": "Metric (Meta)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Time - mio(+)/mpio(-)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum_of_all_the_time_spent_by_mio{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mio)"
    },
    {
     "expr": "(-1) * sum_of_all_the_time_spent_by_mpio{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mpio)"
    }
   ]
  },
  {
   "title": "Count - mio(+)/mpio(-)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_of_mio_count{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mio)"
    },
    {
     "expr": "(-1) * sum_of_mpio_count{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mpio)"
    }
   ]
  },
  {
   "title": "Free Count - mio(+)/mpio(-)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "free_mio_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mio)"
    },
    {
     "expr": "(-1) * free_mpio_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Thread {{thread_name}} (mpio)"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "map_mounted_volume_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Mounted @ {{array_name}}"
    },
    {
     "expr": "map_unmounted_volid{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "Unmounted @ {{array_name}}"
    }
   ]
  },
  {
   "title": "Pending IO CNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "alct_allocctx_pendio_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "Free Segment Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "alct_free_seg_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "GC Victim Segment Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "alct_gcvictim_segid{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "GC Victim Invalid Page Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "alct_victim_invalidpg_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "Flush Pending IO Count - stripe(+)/vsa(-)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "map_stripe_flush_pendio_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "stripe @ {{array_name}}"
    },
    {
     "expr": "(-1) * map_vsa_flush_pendio_cnt{job=\"${CI:raw}\", run_id=\"${run_id:raw}\"}",
     "legendFormat": "vsa @ {{array_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "Log Level Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Info",
     "bucketAggs": [
      {
       "field": "instance_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci:${CI:raw} AND level:Info AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Debug",
     "bucketAggs": [
      {
       "field": "instance_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci:${CI:raw} AND level:Debug AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Warning",
     "bucketAggs": [
      {
       "field": "instance_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci:${CI:raw} AND level:Warning AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Error",
     "bucketAggs": [
      {
       "field": "instance_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci:${CI:raw} AND level:Error AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "instance_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci:${CI:raw} AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "List of Recent 10000 Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 38 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "ci:${CI:raw} AND instance_id.keyword:${run_id:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 3, "x": 18, "y": 46 } }
 ]
}