
ifeq ($(MFS_INTEGRATION_TEST_EN),1)
#VPATH += \
    ./storage/pstore/unit_test \

endif	

ifeq ($(UT_VSTORE_EN),1)
#UT_PATH += \
	$(MFS_TOP_DIR)/storage/vstore/unit_test \

UT_SRCS += \
	ut_mss_ramdisk.cpp \

endif
######################################################

MSS_SRCS += \
	mss_ramdisk.cpp \
