// generated by c_interface_gen module

#include "src/api/Air_c.h"
#include "src/api/Air.h"

extern "C"
void AIR_INITIALIZE(uint32_t cpu_num) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), true>::Initialize(cpu_num);
}

extern "C"
void AIR_ACTIVATE(void) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), true>::Activate();
}

extern "C"
void AIR_DEACTIVATE(void) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), true>::Deactivate();
}

extern "C"
void AIR_FINALIZE(void) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), true>::Finalize();
}

extern "C"
void AIRLOG(uint32_t node_id, uint32_t filter_item, uint64_t node_index, uint64_t value) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), true>::
    LogData(node_id, filter_item, node_index, value);
}

extern "C"
void AIRLOG_FAKE(uint32_t node_id, uint32_t filter_item, uint64_t node_index, uint64_t value) {
    AIR<cfg::GetIntValue(config::ParagraphType::DEFAULT, "AirBuild"), false>::
    LogData(node_id, filter_item, node_index, value);
}
