CC = g++
RM = rm

DEPEND_FILE = $(patsubst %.o,%.d,$@)
OBJECTS = $(addprefix $(OBJDIR)/, $(SRCS:.cpp=.o))

_all : $(OBJECTS)

$(OBJDIR)/%.o: %.cpp
	@echo "================================"
	@echo "= Compiling $(notdir $<)..."
	@echo "================================"
	@$(CC) $(DEBUG) $(INCLUDE) $(CXXFLAGS) $(DEFINE) -c $< -o $@

$(OBJDIR)/%.d: %.cpp
	@$(CC) -MM $(INCLUDE) $(CXXFLAGS) $< -MQ $(@:.d=.o) > $(DEPEND_FILE)

-include $(OBJECTS:.o=.d)
