
name: Package_Upload

on:
  push:
    branches: [ release/v0.12.0  ]
  
  workflow_call:

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'
jobs:
  Upload_Package:
    runs-on: VM
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v1

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: |
        sudo apt update
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}} -c --with-fpic

    - name: package build
      working-directory: ${{github.workspace}}
      run: |
        sudo make package -j8

    - name: Set ouputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: poseidonos-${{ steps.vars.outputs.sha_short }}.deb
        path: |
          ${{github.workspace}}/package/debian/poseidonos.deb

