
name: Package_Upload

on:
  push:
    branches: [ release/v0.12.0  ]
  
  workflow_call:

  workflow_dispatch:
    inputs:
       owner:
          description: 'Repo owner'     
          required: true
          default: 'poseidonos'
       sha:
          description: 'Commit hash'
          required: true
          default: 'main'

jobs:
  Upload_Package:
    runs-on: VM
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - name: Personal repo checkout
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v1
      with:
        repository: ${{ github.event.inputs.owner }}/poseidonos
        ref: ${{ github.event.inputs.sha }}

    - name: Release branch checkout
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_call'}}
      uses: actions/checkout@v1

    - name: Build Setup on push or call
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_call'}}
      working-directory: ${{github.workspace}}/../poseidonos
      run: |
        sudo apt update
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}}/../poseidonos -c --with-fpic

    - name: Build Setup on dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      working-directory: ${{github.workspace}}/../poseidonos
      run: |
        sudo apt update
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.event.inputs.sha}} -d ${{github.workspace}}/../poseidonos -c --with-fpic

    - name: package build
      working-directory: ${{github.workspace}}/../poseidonos
      run: |
        sudo make package -j8
        mv package/debian/poseidonos.deb ${{github.workspace}}

    - name: Set ouputs
      working-directory: ${{github.workspace}}/../poseidonos
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: poseidonos-${{ steps.vars.outputs.sha_short }}.deb
        path: |
          ${{github.workspace}}/poseidonos.deb
