
name: C2-UnitTest_VM

on:
  push:
    branches: [ main, release/v0.12.0 ] 

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'
          
jobs:
  Unit_Test:
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build UT and Run
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/ut_build_run_unittest.sh
        .github/workflows/script/unit/ut_build_run_unittest.sh ${{github.workspace}}

    - name: Copy UT Result to CI Server
      if: always() 
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/copy_ut_result.sh
        .github/workflows/script/unit/copy_ut_result.sh ${{github.workspace}} ${{github.sha}}

    - name: Copy gcov report back to CI server
      if: always() 
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/copy_gcov_report.sh
        .github/workflows/script/unit/copy_gcov_report.sh ${{github.workspace}}

    - uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: 'UnitTestResult/*.xml'

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: UT_LOG
        path: |
          /var/log/pos